######################################################################
#
# File name : cpu_tb_wave.do
# Created on: Sat Apr 20 21:15:44 +0800 2019
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
