######################################################################
#
# File name : cpu_tb_simulate.do
# Created on: Sat Apr 20 21:16:45 +0800 2019
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vsim -voptargs="+acc" +transport_int_delays +pulse_e/0 +pulse_int_e/0 +pulse_r/0 +pulse_int_r/0 -L xil_defaultlib -L simprims_ver -L secureip -lib xil_defaultlib xil_defaultlib.cpu_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {cpu_tb_wave.do}

view wave
view structure
view signals

do {cpu_tb.udo}

run 1000ns
