######################################################################
#
# File name : cpu_tb_compile.do
# Created on: Sat Apr 20 21:16:41 +0800 2019
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"cpu_tb_time_synth.v" \
"../../../../../xiPU.srcs/sim_1/new/cpu_tb.v" \


quit -force

