# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/iram/iram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iram || ORIG_REF_NAME==iram} -quiet] -quiet
