######################################################################
#
# File name : bus_simulate.do
# Created on: Wed Apr 17 20:05:13 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.bus xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {bus_wave.do}

view wave
view structure
view signals

do {bus.udo}

run 1000ns
