######################################################################
#
# File name : bus_wave.do
# Created on: Wed Apr 17 20:04:22 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
