######################################################################
#
# File name : bus_compile.do
# Created on: Wed Apr 17 20:05:10 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../xiPU.srcs/sources_1/new/Regfiles.v" \
"../../../../xiPU.srcs/sources_1/new/alu.v" \
"../../../../xiPU.srcs/sources_1/new/clkDivider.v" \
"../../../../xiPU.srcs/sources_1/new/control.v" \
"../../../../xiPU.srcs/sources_1/new/decoder.v" \
"../../../../xiPU.srcs/sources_1/new/extend.v" \
"../../../../xiPU.srcs/sources_1/new/iram.v" \
"../../../../xiPU.srcs/sources_1/new/mux2.v" \
"../../../../xiPU.srcs/sources_1/new/mux4.v" \
"../../../../xiPU.srcs/sources_1/new/mux5bit.v" \
"../../../../xiPU.srcs/sources_1/new/npc.v" \
"../../../../xiPU.srcs/sources_1/new/pc.v" \
"../../../../xiPU.srcs/sources_1/new/pcPlusData.v" \
"../../../../xiPU.srcs/sources_1/new/ram.v" \
"../../../../xiPU.srcs/sources_1/new/triState.v" \
"../../../../xiPU.srcs/sources_1/new/bus.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

