######################################################################
#
# File name : control_tb_wave.do
# Created on: Tue Apr 16 19:17:12 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
