######################################################################
#
# File name : control_wave.do
# Created on: Tue Apr 16 16:04:16 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
