######################################################################
#
# File name : control_compile.do
# Created on: Tue Apr 16 19:11:40 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../xiPU.srcs/sources_1/new/Regfiles.v" \
"../../../../xiPU.srcs/sources_1/new/add.v" \
"../../../../xiPU.srcs/sources_1/new/alu.v" \
"../../../../xiPU.srcs/sources_1/new/clkDivider20.v" \
"../../../../xiPU.srcs/sources_1/new/clkDivider5.v" \
"../../../../xiPU.srcs/sources_1/new/decoder.v" \
"../../../../xiPU.srcs/sources_1/new/iAddr.v" \
"../../../../xiPU.srcs/sources_1/new/join28.v" \
"../../../../xiPU.srcs/sources_1/new/mux81.v" \
"../../../../xiPU.srcs/sources_1/new/npc.v" \
"../../../../xiPU.srcs/sources_1/new/ram.v" \
"../../../../xiPU.srcs/sources_1/new/triState.v" \
"../../../../xiPU.srcs/sources_1/new/control.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

