######################################################################
#
# File name : control_tb.udo
# Created on: Tue Apr 16 19:17:12 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
