######################################################################
#
# File name : control.udo
# Created on: Tue Apr 16 16:04:16 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
