######################################################################
#
# File name : cpu_tb_wave.do
# Created on: Wed Apr 17 15:45:37 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
