######################################################################
#
# File name : cpu_tb_simulate.do
# Created on: Sun Apr 21 21:53:02 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L dist_mem_gen_v8_0_12 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.cpu_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {cpu_tb_wave.do}

view wave
view structure
view signals

do {cpu_tb.udo}

run 1000ns
